/**
 * Auto-generated sidebar - Docusaurus automatically generates based on file structure
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated sidebar
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate a sidebar from the docs folder structure
    },
  ],
};

module.exports = sidebars;